language: php
php:
- 5.6
- 7.0
env:
- SYMFONY_VERSION=2.6.*
- SYMFONY_VERSION=2.7.*
- SYMFONY_VERSION=2.8.*
- SYMFONY_VERSION=3.0.*
before_script:
- wget http://getcomposer.org/composer.phar
- php -d memory_limit=-1 composer.phar require symfony/symfony:${SYMFONY_VERSION}
- php -d memory_limit=-1 composer.phar install
- phpunit
notifications:
  hipchat:
    rooms:
      secure: chjlQImNw8ufQ1wKeLEZ7XE3oL/OW+I9KOgI8nwja0PwelgAjIRHzHml8n9ZU0weDWTG3TfqxOrpiCEddm5YcJyODfYKPvXHp7ylUlEXemybflCq51W7RWS+2lnadgQuZ7olRhVFTXAVmoYt0VvifpFzb43OGUDNtkhYTitXiuwwYae4xmHT/+TSI621hJvQX5KavyY5H/aCpDi+b27r/mVcIs1FIIDbFu8FHD2A0CvtIgtkQcS4ylFGgOfCDTiNd0M8CU0EiT4X7BuGwWeR5FcaLEjyF83g4naln5zzNC6bN+WkFnkuDOMCKNzY+DbFBbIkw8/8dqPdO8jKbt0E67nlgR8g8nQAGNYFGBlk7/X73fo/WiG2XzSDavI5d2j4ykIirJcP6f9BpoE7Xs+w+JeToW384YUpZsUREzRmxz1neQdEDkQzoYRaVjMgASRG/d1gFHTX0DQBAhkzvG9d5uBALA3sZ6PSj1pNNKFvGo2Xn0dQDY/L4W0Z0SyZFY2c5QFqx+GkZY2223BxmIoQzt/nZEIU/owc70Fz7NPA2WKDhhCI/C8rCkanPCrQxJKu51ROyt9b0sRu9rgS5QjiRzkJ088nVVTAuMT2DFjwLZ66vq7ks31CLpxqou33ctSwg13SfZRpVywUM4arfZ5E35khhIh0+J75Y0bxF04YPV4=
